services:
  - type: web
    name: studiox-cloud
    env: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: python app.py
    plan: free
    autoDeploy: true
